#!/bin/zsh

function mvdw {
   local nfiles=$1
   if [[ ! -n $nfiles ]]; then
        nfiles=1
   fi

   local files=($(ls -d -t1 ~/Downloads/* | head -n $nfiles))
   if [[ ${#files} -lt $nfiles ]]; then
        echo Not enough files were found; else
        for file in $files; do
            mv $file .
        done
   fi
}