#!/bin/zsh

# Check the UID
if [[ $UID -ne 0 ]]; then # normal user
  PR_USER='%F{green}%n%f'
  PR_USER_OP='%F{green}%#%f'
  PR_PROMPT='%f➤ %f'
else # root
  PR_USER='%F{red}%n%f'
  PR_USER_OP='%F{red}%#%f'
  PR_PROMPT='%F{red}➤ %f'
fi

# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats 'on %b'
setopt PROMPT_SUBST

local machine="%F{cyan}%m%f"
local user_host="${PR_USER}"
local current_dir="%B%F{blue}%~%f%b"

PROMPT="${user_host} in ${machine} ${current_dir}
$PR_PROMPT "
RPROMPT=\$vcs_info_msg_0_

# LS colors
export CLICOLOR=1
export LSCOLORS="exfxcxdxbxegedabagacad"
