#!/bin/sh

# use neovim for vim if present
[ -x "$(command -v nvim)" ] && alias vim="nvim"

# navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias lsdw="ls ~/Downloads/"
alias dot="cd ~/repos/dotfiles"

# move all downloads
alias mvdwa="mv ~/Downloads/* ."

# git
alias g="git"
alias gs="git status -sb"
alias gd="git diff --color | sed 's/^\([^-+ ]*\)[-+ ]/\\1/' | less -r"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gca="git commit --amend"
alias gac="git add -A && git commit"
alias gco="git checkout"
alias gp="git push origin HEAD"
alias gpf="git push origin HEAD --force"
alias gl="git pull --prune"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

# conda
alias condaa="conda activate"
alias condad="conda deactivate"
alias jn="base && jupyter notebook"