#!/bin/sh

# use neovim for vim if present
command -v nvim > /dev/null && alias vim="nvim"

# navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# git
alias g="git"
alias gs="git status -sb"
alias gd="git diff --color | sed 's/^\([^-+ ]*\)[-+ ]/\\1/' | less -r"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gca="git commit --amend"
alias gac="git add -A && git commit"
alias gco="git checkout"
alias gp="git push origin HEAD"
alias gpf="git push origin HEAD --force"
alias gl="git pull --prune"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

# tmux
command -v tmux > /dev/null && alias t="tmux"
command -v tmux-sessionizer > /dev/null && alias ts="tmux-sessionizer"
