#!/bin/sh

# brew
eval "$(/opt/homebrew/bin/brew shellenv)"

# disable default mac zsh config
export SHELL_SESSIONS_DISABLE=1

export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"

# dbus
export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"
alias start-dbus="dbus-daemon --fork --session --address=$DBUS_SESSION_BUS_ADDRESS"
alias kill-dbus="killall dbus-daemon"
