#!/bin/sh

# adds `~/.local/bin` to $PATH
if [ -d "$HOME/.local/bin" ]; then
    case ":$PATH:" in
        *":$HOME/.local/bin:"*) :;;
        *) PATH="$HOME/.local/bin:$PATH";;
    esac
fi

# env variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_DESKTOP_DIR="$HOME/Desktop"

export HISTFILE="$XDG_DATA_HOME/history"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GOPATH="$XDG_DATA_HOME/go"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export R_LIBS_USER="$XDG_DATA_HOME/R/library"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"

# defaults
export EDITOR="vim"

# macos
[ "$(uname)" = "Darwin" ] && source "$XDG_CONFIG_HOME/shell/macos"

# pyenv
[ -d $PYENV_ROOT/bin ] && PATH="$PYENV_ROOT/bin:$PATH"
command -v pyenv > /dev/null && eval "$(pyenv init -)"

# switch to zsh
default_shell="$(basename "$SHELL")"
if [ $default_shell != "zsh" ]; then
    if command -v zsh > /dev/null; then
        echo "Default shell is $default_shell, switching to zsh."
        exec zsh
    else
        echo "Default shell is $default_shell and zsh is not present."
    fi
fi

