#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XDG_DOWNLOAD_DIR="$HOME/Downloads"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GOPATH="$XDG_DATA_HOME/go"

# default programs
export EDITOR="nvim"

# macos
[ "$(uname)" = "Darwin" ] && source "$XDG_CONFIG_HOME/shell/macos"

# load aliases
[ -f "$XDG_CONFIG_HOME/shell/aliases" ] && source "$XDG_CONFIG_HOME/shell/aliases"

# adds `~/.local/bin` to $PATH recursively
typeset -U path
path+=(~/.local/bin{,/**/*(N/)})
unsetopt PROMPT_SP
