#!/bin/sh

[ -r "$HOME/.config/shell/env" ] && . "$HOME/.config/shell/env"

# macos config
[ "$(uname)" = "Darwin" ] && . "$XDG_CONFIG_HOME/shell/macos"

# nvim server
mkdir -p "$NVIM_PIPE_DIR"

# init tmux for interactive terminal logins
case $- in *i*)
    [ -t 0 ] && [ -t 1 ] && command -v tmux-init >/dev/null && tmux-init
esac

# switch to zsh (interactive shells only)
case $- in *i*)
    default_shell="$(basename "$SHELL")"
    if [ "$default_shell" != "zsh" ]; then
        if command -v zsh >/dev/null; then
            echo "Default shell is $default_shell, switching to zsh."
            exec zsh
        else
            echo "Default shell is $default_shell and zsh is not present."
        fi
    fi
esac
