# remap C-b to `
unbind C-b
set-option -g prefix `
bind-key ` send-prefix

# history limit
set-option -g history-limit 50000

# allow keybindings to be repeated
set-option -g repeat-time 500

# number windows and panes starting at 1
set-option -g base-index 1
set-option -g pane-base-index 1

# renumber the windows if one is destroyed
set-option -g renumber-windows on

# makes pressing ESC happen without delay
set-option -sg escape-time 0

# open in same directory
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"

# use vi motions in copy mode
set-window-option -g mode-keys vi
# use 'v' to begin selection
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi "C-v" send -X rectangle-toggle
# use 'y' to copy to clipboard, "pbcopy" at the end is needed for macos
bind-key -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
# use ESC to exit copy mode
bind-key -T copy-mode-vi Escape send-keys -X cancel

# vi movements between panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# colors
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# status bar
set -g status-left ""
set -g status-left-length "100"
set -g status-right-length "100"

set -g window-status-format "#[fg=#939ab7,bg=default]█#[fg=#181926,bg=#939ab7]#I#[fg=#939ab7,bg=#363a4f]█#[fg=#cad3f5,bg=#363a4f] #{b:pane_current_path}#{?window_activity_flag, 󱅫,}#{?window_bell_flag, 󰂞,}#{?window_silence_flag, 󰂛,}#{?window_active, 󰖯,}#{?window_last_flag, 󰖰,}#{?window_marked_flag, 󰃀,}#{?window_zoomed_flag, 󰁌,} #[fg=#363a4f,bg=default]█ "
set -g window-status-current-format "#[fg=#c6a0f6,bg=default]█#[fg=#181926,bg=#c6a0f6]#I#[fg=#c6a0f6,bg=#494d64]█#[fg=#cad3f5,bg=#494d64] #{b:pane_current_path}#{?window_activity_flag, 󱅫,}#{?window_bell_flag, 󰂞,}#{?window_silence_flag, 󰂛,}#{?window_active, 󰖯,}#{?window_last_flag, 󰖰,}#{?window_marked_flag, 󰃀,}#{?window_zoomed_flag, 󰁌,} #[fg=#494d64,bg=default]█ "

set -g window-status-activity-style "bg=#eed49f,fg=#181926"
set -g window-status-bell-style "bg=#eed49f,fg=#181926"

set -g pane-border-style "fg=#6e738d"
set -g pane-active-border-style "#{?pane_in_mode,fg=#b7bdf8,#{?pane_synchronized,fg=#c6a0f6,fg=#b7bdf8}}"

set -g message-style "fg=#91d7e3,bg=default,align=centre"
set -g message-command-style "fg=#91d7e3,bg=default,align=centre"
set -g menu-selected-style "fg=#363a4f,bg=#eed49f"

set-window-option -g mode-style "fg=#f5bde6,bg=#5b6078,bold"
set-window-option -g clock-mode-colour "#8aadf4"
set-window-option -g popup-style "bg=#24273a,fg=#cad3f5"
set-window-option -g popup-border-style "fg=#494d64"

set -g status-right "#[fg=#f5bde6,nobold,nounderscore,noitalics]█#[fg=#181926,bg=#f5bde6] #[fg=#f5bde6,bg=#494d64]#[fg=#cad3f5] #{pane_current_command}#[fg=#494d64]█"
set -ag status-right "#[fg=#{?client_prefix,#ed8796,#a6da95},nobold,nounderscore,noitalics]█#[fg=#181926,bg=#{?client_prefix,#ed8796,#a6da95}] #[fg=#{?client_prefix,#ed8796,#a6da95},bg=#494d64]#[fg=#cad3f5] #S#[fg=#494d64]█"

# fix issues with transparency
set-option -g status-style bg=default
